// ============================================================================
// STARTER NOTE — Station 2.
//
// Data access for users, following the same pattern as requests.store.js:
// parameterized queries, rows in/rows out, optional `db` for transactions.
//
// Decisions already made for you by migration 003:
//   * id, role and created_at are generated by the database;
//   * role is NOT a parameter of insertUser — registration cannot choose it.
// ============================================================================
import { pool } from '../../database/pool.js';

const USER_COLUMNS = `
  id,
  email,
  role,
  created_at
`;

export async function findByEmail(email, db = pool) {
  const result = await db.query(
    `SELECT id, email, password_hash, role, created_at
     FROM users WHERE email = $1`,
    [email]
  );
  return result.rows[0] ?? null;
}

export async function findById(id, db = pool) {
  const result = await db.query(
    `SELECT id, email, password_hash, role, created_at
     FROM users WHERE id = $1`,
    [id]
  );
  return result.rows[0] ?? null;
}

export async function insertUser({ email, passwordHash }, db = pool) {
  const result = await db.query(
    `INSERT INTO users (email, password_hash)
     VALUES ($1, $2)
     RETURNING ${USER_COLUMNS}`,
    [email, passwordHash]
  );
  return result.rows[0];
}
